language: python
python:
  #- "2.6" # Cannot do 2.6 with system_site_packages
  - "2.7"
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
  - sudo apt-get install -y protobuf-compiler valgrind screen
  - ./start_influx_service.sh
install:
  - "pip install -r requirements.txt"
  - "pip install -r mongodb-requirements.txt"
  - "pip install -r influxdb-requirements.txt"
script: ./test.sh
virtualenv:
  system_site_packages: true
services:
  - mongodb

