
[[constraint]]
  branch = "master"
  name = "github.com/influxdata/kapacitor"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_golang"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/client_model"
