site_name: Morgoth - Documentation
site_favicon: favicon.ico
site_author: Nathaniel Cook
site_url: http://docs.morgoth.io/docs/
docs_dir: src
repo_url: https://github.com/nathanielc/morgoth/
pages:
  - index.md
  - overview.md
  - getting-started.md
  - configuration.md
  - concepts/detection_framework.md
  - concepts/fingerprints.md
theme: readthedocs
theme_dir: custom_theme
